### ISSUE TITLE
Instructions for getting Reddit API keys?

### ISSUE THREAD

**Issue by sshleifer** [alexa/Topical-Chat#1]
I am getting here

![image](https://user-images.githubusercontent.com/6045025/65294199-c4d99980-db12-11e9-82d7-9aeede5e7321.png)

after a google form. What do I put for redirect URI? Is this what you guys did?

Thanks in advance!

**Comment by mohshmi** [comment]
Check out the documentation of the praw package.

https://praw.readthedocs.io/en/v3.6.0/pages/oauth.html?highlight=redirect

**Comment by sshleifer** [comment]
Thanks!
