### ISSUE TITLE
 ASR training corpus for N-gram simulator (TopicalChatASR)

### ISSUE THREAD

**Issue by willburr** [alexa/Topical-Chat#10]
From the README, the N-gram was trained using _transcribed ASR output from an internal user study_. Would it be possible for this transcribed ASR corpus to be released? This would allow for experimenting with other ASR error simulation approaches. 
Thank you!

**Comment by g-karthik** [comment]
@willburr thanks again for reaching out and your interest in this work! Unfortunately, we wouldn't be able to release the transcribed ASR corpus that was used to train the simulator. If you're interested in other ASR error simulation approaches, we'd recommend trying out those that wouldn't necessarily require the same corpus used to train our simulator. You could use approaches such as phonetic similarity swap, for instance.

**Comment by willburr** [comment]
Thank you, that makes sense!
