### ISSUE TITLE
Use of train.json

### ISSUE THREAD

**Issue by AlkisPis** [alexa/Topical-Chat#13]
This is not actually an issue but rather a query that I could not post anywhere else.
My question is this: As 'train.json' is a chat dataset containing conversetions that are quite verbose and complex, what Python chatbot package(s) can handle it best, i.e. more effectively? 
(I have already used and treained the chatbot from the 'chatbot-webraft' package, which works OK but the prompt-response reault is not so good.)

**Comment by g-karthik** [comment]
You can try playing with Hugging Face's `transformers` library.
