### ISSUE TITLE
Starter code for ParlAI integration?

### ISSUE THREAD

**Issue by sshleifer** [alexa/Topical-Chat#3]
Paper references training transformers using `ParlAI`. Is there any starter code available or at least a description of what needs to be done?

Looking at ParlAI, I'm guessing that you guys made a task with a custom teacher like `WizardOfWikipediaTeacher` https://github.com/facebookresearch/ParlAI/blob/0630ee4cae335ad8f4f304dd2ec873e786de5b8e/parlai/tasks/wizard_of_wikipedia/agents.py#L97

Any help getting started would be much appreciated!

**Comment by bhedayat** [comment]
Yes we made a task similar to what you linked (https://github.com/facebookresearch/ParlAI/blob/0630ee4cae335ad8f4f304dd2ec873e786de5b8e/parlai/tasks/wizard_of_wikipedia/agents.py#L97)

In terms of modeling we used something similar to the TransformerAgent (https://github.com/facebookresearch/ParlAI/blob/0630ee4cae335ad8f4f304dd2ec873e786de5b8e/parlai/agents/transformer/transformer.py#L255)

The code for Wizard of Wikipedia is now open source (https://github.com/facebookresearch/ParlAI/tree/0630ee4cae335ad8f4f304dd2ec873e786de5b8e/projects/wizard_of_wikipedia)
And can be another good starting point.

**Comment by sshleifer** [comment]
Thanks!

**Comment by sshleifer** [comment]
Are you guys planning on releasing anything?
