### ISSUE TITLE
How to calculate the metric "n-gram diversity" as mentioned in your paper?

### ISSUE THREAD

**Issue by liuslnlp** [alexa/Topical-Chat#7]
> ... For automated evaluation, we consider metrics such as per- plexity (PPL), unigram F1 of model prediction with ground-truth response and **n-gram diversity** (Div.) [8]. In Table 3, we observe that all ...

I didn't find how to calculate it in reference [8]

**Comment by g-karthik** [comment]
@WiseDoge there are multiple variants for diversity - utterance-level and corpus-level. In the paper, we computed utterance-level diversity. See [here](https://github.com/neural-dialogue-metrics/Distinct-N/blob/master/distinct_n/metrics.py#L3) for an implementation.
