### ISSUE TITLE
N-gram simulator used (TopicalChatASR)

### ISSUE THREAD

**Issue by willburr** [alexa/Topical-Chat#9]
This is a question regarding the ASR simulations in TopicalChatASR. 
> We used the ASR error simulator method based on n-gram confusion matrix and trained the simulator on transcribed ASR output from an internal user study.

From inspecting the simulations, it looks as though the same simulator is applied to both the training and test sets (i.e. using the same learned confusions). Could you confirm whether this is the case or were separate simulators applied to the different dataset splits? 

Thank you!

**Comment by g-karthik** [comment]
@willburr thanks for your interest in our work!

Indeed, the same simulator was applied to the train/valid/test splits. Note that the simulation process is stochastic - so using the same simulator doesn't mean simulating exactly the same errors, but yes it could result in similar commonly observed n-gram confusions.

We've also released two small-scale test sets with actual ASR errors though, so ideally those would act as noisy "held-out" test sets.

Let me know if that helps and if you have any further follow-up questions!

**Comment by willburr** [comment]
Yes that helps! Thank you for clarifying.
